// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3Genie2.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208175133_bd-init")]
    partial class bdinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembreId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<bool>("RenouvellementAuto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MembreId")
                        .IsUnique()
                        .HasFilter("[MembreId] IS NOT NULL");

                    b.HasIndex("PlanId");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.AbonnementPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixMensuel")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AbonnementPlans");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.CarteCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("CartesCredits");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MembreId")
                        .IsUnique();

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Cote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("MembreId");

                    b.ToTable("Cotes");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffichePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnneeSortie")
                        .HasColumnType("int");

                    b.Property<string>("BandeAnnoncePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.FilmCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("PersonneId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("PersonneId");

                    b.ToTable("FilmCredits");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypePersonne")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.PisteAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("PistesAudio");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.PisteSousTitre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("PistesSousTitre");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Visionnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<int>("ModeAcces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("MembreId");

                    b.ToTable("Visionnements");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Abonnement", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Membre", "Membre")
                        .WithOne("Abonnement")
                        .HasForeignKey("TP3Genie2.Domain.Entities.Abonnement", "MembreId");

                    b.HasOne("TP3Genie2.Domain.Entities.AbonnementPlan", "Plan")
                        .WithMany("Abonnements")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.CarteCredit", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Compte", "Compte")
                        .WithMany("CartesCredits")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Compte", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Membre", "Membre")
                        .WithOne("Compte")
                        .HasForeignKey("TP3Genie2.Domain.Entities.Compte", "MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Cote", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Film", "Film")
                        .WithMany("Cotes")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP3Genie2.Domain.Entities.Membre", "Membre")
                        .WithMany("Cotes")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Film", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Films")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.FilmCredit", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Film", "Film")
                        .WithMany("Credits")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP3Genie2.Domain.Entities.Personne", "Personne")
                        .WithMany("FilmCredits")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Membre", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Membre")
                        .HasForeignKey("TP3Genie2.Domain.Entities.Membre", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.PisteAudio", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Film", "Film")
                        .WithMany("PistesAudio")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.PisteSousTitre", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Film", "Film")
                        .WithMany("SousTitres")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Visionnement", b =>
                {
                    b.HasOne("TP3Genie2.Domain.Entities.Film", "Film")
                        .WithMany("Visionnements")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP3Genie2.Domain.Entities.Membre", "Membre")
                        .WithMany("Visionnements")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.AbonnementPlan", b =>
                {
                    b.Navigation("Abonnements");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Compte", b =>
                {
                    b.Navigation("CartesCredits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Film", b =>
                {
                    b.Navigation("Cotes");

                    b.Navigation("Credits");

                    b.Navigation("PistesAudio");

                    b.Navigation("SousTitres");

                    b.Navigation("Visionnements");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Membre", b =>
                {
                    b.Navigation("Abonnement");

                    b.Navigation("Compte")
                        .IsRequired();

                    b.Navigation("Cotes");

                    b.Navigation("Visionnements");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Personne", b =>
                {
                    b.Navigation("FilmCredits");
                });

            modelBuilder.Entity("TP3Genie2.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Membre");
                });
#pragma warning restore 612, 618
        }
    }
}
